-- -----------------------------------------------------
-- Schema full-stack-ecommerce-football
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `full-stack-ecommerce-football`;

CREATE SCHEMA `full-stack-ecommerce-football`;
USE `full-stack-ecommerce-football` ;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce-football`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce-football`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce-football`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce-football`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO product_category(category_name) VALUES ('Footballs');
INSERT INTO product_category(category_name) VALUES ('Gloves');
INSERT INTO product_category(category_name) VALUES ('Boots');
INSERT INTO product_category(category_name) VALUES ('Leggins');

-- -----------------------------------------------------
-- Footballs
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1000', 'T-model', 'Where it all began. The T-model – named after that distinctive shape of panel – is Year Zero for what modern balls would become, used in the second half of the inaugural World Cup final in 1930. Weve come a long, long way…', 'assets/images/products/footballs/football.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1001', 'Nike Maxim', 'One of the classier efforts that Nike have provided the Premier League in their 20-odd years of supplying the match ball, the Maxim combined red and blue for darker panels. It looked superb and the design still holds up today. ', 'assets/images/products/footballs/football.png', 1, 100, 20.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1002', 'Mitre Delta Max', 'For some, Mitre are old-fashioned and fusty. This FA Cup ball, however, was anything but: the red and white swirls made pretty patterns as it flew through the air – a great effort. ', 'assets/images/products/footballs/football.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1003', 'Puma Adrenalina', 'Puma havent been in the ball game as long as others but their early La Liga products have been well-received. This is a particular highlight and one that has lit up Clasicos. ', 'assets/images/products/footballs/football.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1004', 'Nike Total 90 Tracer', 'Another simple design from Nike, the Tracer was the Berba ball: the Volt-infused sphere that Dimitar dominated with to send United to another title. Its stripped back and sophisticated. ', 'assets/images/products/footballs/football.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1005', 'Versace Barocco Soccer Ball', 'The kind of thing youd expect Zlatan Ibrahimovic to have in his living room, this might be the most extra football of all time. Its never been used in a proper match', 'assets/images/products/footballs/football.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1006', 'Adidas Finale Cardiff', 'The Adidas Finale has become an icon of the game – so its only right that the roadshow of Champions League finals should adapt the match ball to its identity.', 'assets/images/products/footballs/football.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1007', 'Mitre Halftime Slice', 'The half-time orange may be something that you havent considered for roughly 25 years but the Mitre tribute to an old tradition is unforgettable', 'assets/images/products/footballs/football.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1008', 'Derbystar Brilliant APS 2017', 'Derbystar, the official suppliers to the Eredivisie teamed up with renowned tattoo artist Henk Schiffmacher for this one. The aptly-named Brilliant celebrated the 60th birthday of the Dutch division – and its suitably beautiful.', 'assets/images/products/footballs/football.png', 1, 100, 25.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1009', 'Nike Seitiro', 'The geometric patterns on the Seitiro were reminiscent of burning comets plummeting to the Earth – and thats exactly what this thing looked like when Sergio Aguero smashed it in against QPR in dramatic fashion.', 'assets/images/products/footballs/football.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1010', 'Adidas Wawa Aba', 'With imagination in short supply at Adidas around this time – they were still using their ball design from two years ago – someone had a genius idea for the 2008 Africa Cup of Nations. Just look at this ball.', 'assets/images/products/footballs/football.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1011', 'Molten Europa League', 'Molten dont make kits but have somehow become the ball supplier to UEFAs second-biggest club tournament. They dont show themselves up either – this particular Europa ball was a fiery beauty.', 'assets/images/products/footballs/football.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1012', 'Nike Strike Phantom Scorpion', 'A tribute to the shiny sphere that Ronaldinho fixed his hair in the reflection of in 2002 Nike Cage ads, the Scorpion version of the Nike Flight was pure nostalgia.', 'assets/images/products/footballs/football.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FOOT-BALL-1013', 'Adidas Nativo 21', 'Its called a football. Adidas made that particularly clear when giving MLS their designated soccer sphere for 2021, that featured stars, stripes, red, white and blue, somehow, without looking in the least bit tacky.', 'assets/images/products/footballs/football.png', 1, 100, 19.99, 1, NOW());

-- -----------------------------------------------------
-- Gloves
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1000', 'Adidas Predator Edge Pro', 'Adidas has used premium-grade URG 2.0 rubber foam for the palm area that feels tacky enough to use in wet conditions. The foam has great shock-absorption properties and you get an excellent ball feel.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1001', 'Puma Future: One Grip', 'In terms of looks, the One Grip NC is one of the coolest goalie gloves you can pick. This glove has a negative fit with a dual grip latex that provides a solid grip. It feels comfortable, and the ergonomics are top-notch.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1002', 'Nike Phantom Elite', 'Nike uses the All-Conditions Control (ACC) foam technology and a true negative cut to make this one of their best gloves. The design provides a good combination of comfort and mobility.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1003', 'Rectrix 1.0', 'If you are looking for high-quality goalie gloves that offer great value, the Rectix 1.0 deserves a closer look. The simplistic design has a negative cut, robust wrist straps, and good finger support.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1004', 'UHLSport Supergrip Reflex', 'The Supergrip from UHLSport packs a ton of new technology that makes it one of the best goalkeeper gloves for wet as well as dry conditions.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1005', 'Nike Mercurial Goalkeeper Touch Elite', 'The Mercurial Touch Elite cuts through the bulk of traditional gloves to offer a minimalist design and great performance in all conditions. Nike uses ACC (All-Conditions Control) technology.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1006', 'Sondico Aqua Elite', 'While this pair of goalkeeper gloves from Sondico are not the best match gloves you can pick, they do offer excellent value.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1007', 'Reusch Pure Contact Fusion', 'The Pure Contact gloves from Reusch not only look fresh but also offer a premium grip with a new foam formulation. It uses a modified negative cut to provide a comfortable fit.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1008', 'Storelli ExoShield Gladiator Pro 3', 'As the name indicates, the Storelli Exoshield are heavy-duty gloves that are great for match play. Storelli has added 3mm of impact foam and high-quality latex to combine a high-quality grip along with shock absorption.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1009', 'Nike Goalkeeper Match', 'Theres no need to break the bank to ensure youve got a sturdy pair of gloves to see you through your stint between the posts - the Nike Goalkeeper Match delivers well beyond its price, providing all-around command and control at an affordable price.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1010', 'PUMA King RC', 'Want to add a shot of retro style to your gear? This nifty black-and-white set from PUMA brings back monochrome glory and does a great job even with its distinctive style on top. Simple yet effective - its guaranteed to deliver.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1011', 'Nike Goalkeeper Phantom Shadow', 'Any goalkeeper will tell you that blocking a hot shot fired in like a rocket from anywhere on the pitch can sting, but these Phantom Shadow gloves from Nike take the bite out of any opposing players bark.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1012', 'PUMA Ultra Grip 1', 'If youre looking for a revolutionary and innovative goalkeeper glove, this is it. Run the way your game with these ULTRA Grip 1 hybrid goalkeeper gloves. Theyre lightweight and flexible to boost agility.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GLOVE-1013', 'Nike Mercurial Goalkeeper Touch Elite', 'The need to streamline performance has made its way through almost every piece of attire you can find in a kit bag - and the Mercurial Goalkeeper Touch Elite proves that goalkeeper gloves are no exception.', 'assets/images/products/gloves/glove.png', 1, 100, 18.99, 2, NOW());

-- -----------------------------------------------------
-- Boots
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1000', 'Nike Premier 3', 'The latest Nike Premier series is a hit with us. It’s always been a budget option, and it remains that way for the third installment.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1001', 'Pantofola dOro Lazzarini x World Cup', 'Ah, the ‘Golden Slippers’ are back in our list. It’s impossible to ignore Pantofolo d’Oro’s premium leather boots, and they really don’t get much more supple than these Italian gems.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1002', 'Nike Tiempo Legend 9', 'Well, this season they’ll be wearing this unbelievable silo from Nike, the Tiempo Legend 9. Leah Williamson, Virgil Van Dijk, Henderson, De Vrij. They’re all in them.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1003', 'Adidas Copa Mundial', 'The oldest and most classic of all. It’s impossible to talk about the best football boots of the year without mentioning the adidas Copa Mundial.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1004', 'New Balance Furon V7', 'This boot is a lightweight synthetic creation, with available takedown silos for all budgets in a range of colourways and a choice of FG/SG/TF soleplates.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1005', 'Adidas X Speedportal', 'The upgraded adidas X Speedportal is, as you’d imagine, a boot built for unadulterated speed.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1006', 'Puma Ultra', 'They’re available in a range of surface types and colourways with some extremely lively ones thrown in the mix, for the more exuberant players amongst us.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1007', 'Adidas Copa Pure', 'The modern adidas Copa Pure is a work of art. Smooth lines, Fusionskin cow leather comfort and incredible heritage looks.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1008', 'Mizuno Alpha', 'This premium model offers the greatest comfort of any boot on the market, in a range of colourways and surface types including SG, FG and even indoor.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1009', 'Adidas Predator Accelerator x PD25', 'This adidas Predator Accelerator was the highlight for us, an iconic boot reimagined. It’s just majestic.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1010', 'Nike Mercurial Superfly 9', 'That Kylian Mbappé lad, he’s not bad is he? A slight understatement, some may say.Turns out, he wears Nike Mercurial Superfly 9 boots. And they’re not too shabby either', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1011', 'Adidas Predator Accuracy', 'The Accuracy is sleeker and more finessed than the earlier Edge, which relied more on power. They have to be, as mercurial stars Bellingham and Zelem wear them.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1012', 'Nike Phantom GX', 'Worn by top players Harry Kane, Ella Toone and Erling Haaland, it’s not hard to see why you should grab yourself a pair.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOTS-1013', 'Puma Future', 'Their latest installment has unparalleled levels of lockdown and support, something which superstars Neymar, Ederson and Alexandra Popp can all attest to.', 'assets/images/products/boots/boot.png', 1, 100, 17.99, 3, NOW());

-- -----------------------------------------------------
-- Leggins
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1000', 'Puma - Razor', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1001', 'Nike - Drift', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1002', 'Nike - Power', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1003', 'Adidas - Gloom', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1004', 'New Balance - Night', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1005', 'Adidas - Trust', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1006', 'Puma - King', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1007', 'Kipsta - Simple', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1008', 'Fila - White', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1009', 'Kipsta - Kid', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1010', 'Puma - Slide', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1011', 'Jordan - Three', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1012', 'Nike - CR7', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LEGGINS-1013', 'Adidas - Messi', 'Following observations from the field, our team of enthusiasts found the importance of the support offered by leggings. They are designed from polyester and elastane, to avoid slipping at the level of the calf.', 'assets/images/products/leggins/leggin.png', 1, 100, 16.99, 4, NOW());

